// Brevo Form Integration Service
// Form endpoint generated by Brevo for Form Bugambilias

export const BREVO_ACTION_URL =
  "https://6a4b9728.sibforms.com/serve/MUIFAPmPU1nhL_msIQzXxb6srr0nZWplC9DH0NsmXo9QYUTx1wCqN55qsQnW86v42myy0XJiXBIHaYSqKkEkDU7Eqy4MGsOaRHSLEPlSvu58RtTkFP_0pkuCJZPV7QyNCrE3SvbOZrrUUdtSHk9dZ14Z9MoPe9kInSwusSaJqdk3VXn6BgfEj434jUVSP4cj72dPvHeVNhW2PvEl3A==";

export interface BrevoLeadData {
  lead?: string;
  nombre?: string;
  apellidos?: string;
  correo?: string;
  email?: string;
  celular?: string;
  whatsapp?: string;
  countryCode?: string;
}

/**
 * Sends lead information directly to Brevo's form subscription endpoint.
 */
export async function sendToBrevo(leadData: BrevoLeadData): Promise<boolean> {
  try {
    const fullName = (leadData.lead || "").trim();
    let nombre = (leadData.nombre || "").trim();
    let apellidos = (leadData.apellidos || "").trim();

    if (!nombre && fullName) {
      const parts = fullName.split(" ").filter(Boolean);
      nombre = parts[0] || fullName;
      apellidos = parts.slice(1).join(" ") || "";
    }

    const email = (leadData.correo || leadData.email || "").trim();
    const rawPhone = (leadData.celular || leadData.whatsapp || "").trim();

    let cleanPhone = rawPhone.replace(/\D/g, "");
    let countryCode = leadData.countryCode || "+51";

    if (cleanPhone.startsWith("51") && cleanPhone.length === 11) {
      cleanPhone = cleanPhone.substring(2);
      countryCode = "+51";
    }

    const params = new URLSearchParams();
    params.append("NOMBRE", nombre);
    params.append("APELLIDOS", apellidos);
    params.append("EMAIL", email);
    params.append("WHATSAPP__COUNTRY_CODE", countryCode);
    params.append("WHATSAPP", cleanPhone);
    params.append("email_address_check", "");
    params.append("locale", "es");

    console.log("[Brevo Service] Forwarding lead data to Brevo:", {
      nombre,
      apellidos,
      email,
      countryCode,
      cleanPhone,
    });

    await fetch(BREVO_ACTION_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: params.toString(),
      mode: "no-cors",
    });

    console.log("[Brevo Service] Lead data sent to Brevo successfully.");
    return true;
  } catch (error) {
    console.error("[Brevo Service] Network or processing error sending to Brevo:", error);
    return false;
  }
}

// Raw Brevo Form HTML preserved for reference or rendering if ever needed
export const BREVO_FORM_RAW_HTML = `
<!-- Begin Brevo Form -->
<link rel="stylesheet" href="https://sibforms.com/forms/end-form/build/sib-styles.css">
<div class="sib-form">
  <div id="sib-form-container" class="sib-form-container">
    <div id="sib-container">
      <form id="sib-form" method="POST" action="${BREVO_ACTION_URL}" data-type="subscription">
        <input type="text" id="NOMBRE" name="NOMBRE" placeholder="NOMBRE" />
        <input type="text" id="APELLIDOS" name="APELLIDOS" placeholder="APELLIDOS" />
        <input type="text" id="EMAIL" name="EMAIL" placeholder="EMAIL" required />
        <select name="WHATSAPP__COUNTRY_CODE"><option value="+51">+51 PE</option></select>
        <input type="tel" id="WHATSAPP" name="WHATSAPP" placeholder="WHATSAPP" />
        <input type="text" name="email_address_check" value="" class="input--hidden" />
        <input type="hidden" name="locale" value="es" />
        <button type="submit">Enviar</button>
      </form>
    </div>
  </div>
</div>
`;
